[rule]
description = """
Identifies instances where a dynamic library (dylib) is loaded by an untrusted process on macOS. Threat actors may abuse
this technique by leveraging compromised or malicious processes to load dylibs for code injection, persistence, or
privilege escalation. When a dylib is loaded by an untrusted or unsigned process, it may indicate that the process
itself is malicious or has been tampered with, bypassing security mechanisms that rely on process code signing to
validate the integrity and authenticity of the process.
"""
id = "f8367f4d-08ca-4865-840c-7cb965a14eeb"
license = "Elastic License v2"
name = "Dylib Load via Untrusted Process in Temporary Directory"
os_list = ["macos"]
version = "1.0.19"

query = '''
library where event.action == "load" and 
 process.executable : ("/tmp/*", "/var/tmp/*", "/private/tmp/*") and
 process.code_signature.trusted == false and
 not process.code_signature.status : "errorCode_endpoint*" and 
 not Effective_process.executable : ("/opt/homebrew/*", "/nix/store/*") and
 not dll.path : ("/Applications/Xcode.app/*", "/Applications/Xcode-*.app/*", "/opt/homebrew/*") and
 not (Effective_process.executable : "/nix/store/*" and dll.path : "/nix/store/*")
'''

min_endpoint_version = "8.11.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1574"
name = "Hijack Execution Flow"
reference = "https://attack.mitre.org/techniques/T1574/"


[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

[internal]
min_endpoint_version = "8.11.0"
